In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\athlete_events.csv")
region_df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\noc_regions.csv")

In [3]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
123389,62351,Viktoriya Aleksandrovna Komova,F,17.0,150.0,48.0,Russia,RUS,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Women's Uneven Bars,NaN
207288,104013,Kristina Sabasteanski (-Viljanen),F,32.0,157.0,55.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Biathlon,Biathlon Women's 4 x 7.5 kilometres Relay,NaN
137800,69264,"Timothy Charles ""Tim"" Lewis",M,25.0,183.0,76.0,United States,USA,1988 Summer,1988,Summer,Seoul,Athletics,Athletics Men's 20 kilometres Walk,NaN
233834,117277,Nelly Syro Posada,F,15.0,163.0,53.0,Colombia,COL,1968 Summer,1968,Summer,Mexico City,Swimming,Swimming Women's 200 metres Individual Medley,NaN
270585,135330,Valery Viktorovich Zubanov,M,21.0,184.0,82.0,Soviet Union,URS,1972 Summer,1972,Summer,Munich,Sailing,Sailing Mixed Two Person Heavyweight Dinghy,NaN

In [4]:
region_df.sample(5)

     NOC              region notes
58   DOM  Dominican Republic   NaN
68   FIN             Finland   NaN
40   CHI               Chile   NaN
100  ITA               Italy   NaN
60   EGY               Egypt   NaN

In [6]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [8]:
region_df.isnull().sum()

NOC         0
region      3
notes     209
dtype: int64

In [9]:
region_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

In [10]:
df.duplicated().sum()

np.int64(1385)

In [12]:
df.shape

(271116, 15)

In [13]:
df.drop_duplicates(inplace =True)

In [14]:
df.shape

(269731, 15)

In [16]:
df = df[df.Season == 'Summer']

In [17]:
df.shape

(221167, 15)

In [21]:
df = pd.merge(df, region_df, on = "NOC", how="outer")

In [23]:
df['region'].unique()

array(['Afghanistan', 'Curacao', 'Albania', 'Algeria', 'Andorra',
       'Angola', 'Antigua', 'Australia', 'Argentina', 'Armenia', 'Aruba',
       'American Samoa', 'Austria', 'Azerbaijan', 'Bahamas', 'Bangladesh',
       'Barbados', 'Burundi', 'Belgium', 'Benin', 'Bermuda', 'Bhutan',
       'Bosnia and Herzegovina', 'Belize', 'Belarus', 'Czech Republic',
       'Boliva', 'Botswana', 'Brazil', 'Bahrain', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Central African Republic', 'Cambodia', 'Canada',
       'Cayman Islands', 'Republic of Congo', 'Chad', 'Chile', 'China',
       'Ivory Coast', 'Cameroon', 'Democratic Republic of the Congo',
       'Cook Islands', 'Colombia', 'Comoros', 'Cape Verde', 'Costa Rica',
       'Croatia', 'Greece', 'Cuba', 'Cyprus', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea',
       'El Salvador', 'Spain', 'Estonia', 'Ethiopia', 'Russia', 'Fiji',
       'Finland', 'France', 'Germany', 'Micronesia', 'Gabon', 'Gambia',
       'UK', 'Guinea-Bissau', 'Georgia', 'Equatorial Guinea', 'Ghana',
       'Grenada', 'Guatemala', 'Guinea', 'Guam', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Indonesia', 'India',
       'Individual Olympic Athletes', 'Iran', 'Ireland', 'Iraq',
       'Iceland', 'Israel', 'Virgin Islands, US', 'Italy',
       'Virgin Islands, British', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Kiribati', 'South Korea',
       'Kosovo', 'Saudi Arabia', 'Kuwait', 'Laos', 'Latvia', 'Libya',
       'Liberia', 'Saint Lucia', 'Lesotho', 'Lebanon', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malaysia', 'Morocco',
       'Malawi', 'Moldova', 'Maldives', 'Mexico', 'Mongolia',
       'Marshall Islands', 'Macedonia', 'Mali', 'Malta', 'Montenegro',
       'Monaco', 'Mozambique', 'Mauritius', 'Mauritania', 'Myanmar',
       'Namibia', 'Nicaragua', 'Netherlands', 'Nepal', 'Nigeria', 'Niger',
       'Norway', 'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Palestine', 'Palau',
       'Papua New Guinea', 'Poland', 'Portugal', 'North Korea',
       'Puerto Rico', 'Qatar', 'Zimbabwe', nan, 'Romania', 'South Africa',
       'Rwanda', 'Samoa', 'Serbia', 'Senegal', 'Seychelles', 'Singapore',
       'Saint Kitts', 'Sierra Leone', 'Slovenia', 'San Marino',
       'Solomon Islands', 'Somalia', 'Sri Lanka', 'South Sudan',
       'Sao Tome and Principe', 'Sudan', 'Switzerland', 'Suriname',
       'Slovakia', 'Sweden', 'Swaziland', 'Syria', 'Tanzania', 'Tonga',
       'Thailand', 'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Togo',
       'Taiwan', 'Trinidad', 'Tunisia', 'Turkey', 'United Arab Emirates',
       'Uganda', 'Ukraine', 'Uruguay', 'USA', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Saint Vincent', 'Yemen', 'Zambia'],
      dtype=object)