In [91]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\athlete_events.csv")
region_df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\noc_regions.csv")

In [3]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
123389,62351,Viktoriya Aleksandrovna Komova,F,17.0,150.0,48.0,Russia,RUS,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Women's Uneven Bars,NaN
207288,104013,Kristina Sabasteanski (-Viljanen),F,32.0,157.0,55.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Biathlon,Biathlon Women's 4 x 7.5 kilometres Relay,NaN
137800,69264,"Timothy Charles ""Tim"" Lewis",M,25.0,183.0,76.0,United States,USA,1988 Summer,1988,Summer,Seoul,Athletics,Athletics Men's 20 kilometres Walk,NaN
233834,117277,Nelly Syro Posada,F,15.0,163.0,53.0,Colombia,COL,1968 Summer,1968,Summer,Mexico City,Swimming,Swimming Women's 200 metres Individual Medley,NaN
270585,135330,Valery Viktorovich Zubanov,M,21.0,184.0,82.0,Soviet Union,URS,1972 Summer,1972,Summer,Munich,Sailing,Sailing Mixed Two Person Heavyweight Dinghy,NaN

In [4]:
region_df.sample(5)

     NOC              region notes
58   DOM  Dominican Republic   NaN
68   FIN             Finland   NaN
40   CHI               Chile   NaN
100  ITA               Italy   NaN
60   EGY               Egypt   NaN

In [6]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [8]:
region_df.isnull().sum()

NOC         0
region      3
notes     209
dtype: int64

In [9]:
region_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

In [10]:
df.duplicated().sum()

np.int64(1385)

In [12]:
df.shape

(271116, 15)

In [13]:
df.drop_duplicates(inplace =True)

In [14]:
df.shape

(269731, 15)

In [16]:
df = df[df.Season == 'Summer']

In [17]:
df.shape

(221167, 15)

In [21]:
df = pd.merge(df, region_df, on = "NOC", how="outer")

In [23]:
df['region'].unique()

array(['Afghanistan', 'Curacao', 'Albania', 'Algeria', 'Andorra',
       'Angola', 'Antigua', 'Australia', 'Argentina', 'Armenia', 'Aruba',
       'American Samoa', 'Austria', 'Azerbaijan', 'Bahamas', 'Bangladesh',
       'Barbados', 'Burundi', 'Belgium', 'Benin', 'Bermuda', 'Bhutan',
       'Bosnia and Herzegovina', 'Belize', 'Belarus', 'Czech Republic',
       'Boliva', 'Botswana', 'Brazil', 'Bahrain', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Central African Republic', 'Cambodia', 'Canada',
       'Cayman Islands', 'Republic of Congo', 'Chad', 'Chile', 'China',
       'Ivory Coast', 'Cameroon', 'Democratic Republic of the Congo',
       'Cook Islands', 'Colombia', 'Comoros', 'Cape Verde', 'Costa Rica',
       'Croatia', 'Greece', 'Cuba', 'Cyprus', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea',
       'El Salvador', 'Spain', 'Estonia', 'Ethiopia', 'Russia', 'Fiji',
       'Finland', 'France', 'Germany', 'Micronesia', 'Gabon', 'Gambia',
       'UK', 'Guinea-Bissau', 'Georgia', 'Equatorial Guinea', 'Ghana',
       'Grenada', 'Guatemala', 'Guinea', 'Guam', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Indonesia', 'India',
       'Individual Olympic Athletes', 'Iran', 'Ireland', 'Iraq',
       'Iceland', 'Israel', 'Virgin Islands, US', 'Italy',
       'Virgin Islands, British', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Kiribati', 'South Korea',
       'Kosovo', 'Saudi Arabia', 'Kuwait', 'Laos', 'Latvia', 'Libya',
       'Liberia', 'Saint Lucia', 'Lesotho', 'Lebanon', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malaysia', 'Morocco',
       'Malawi', 'Moldova', 'Maldives', 'Mexico', 'Mongolia',
       'Marshall Islands', 'Macedonia', 'Mali', 'Malta', 'Montenegro',
       'Monaco', 'Mozambique', 'Mauritius', 'Mauritania', 'Myanmar',
       'Namibia', 'Nicaragua', 'Netherlands', 'Nepal', 'Nigeria', 'Niger',
       'Norway', 'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Palestine', 'Palau',
       'Papua New Guinea', 'Poland', 'Portugal', 'North Korea',
       'Puerto Rico', 'Qatar', 'Zimbabwe', nan, 'Romania', 'South Africa',
       'Rwanda', 'Samoa', 'Serbia', 'Senegal', 'Seychelles', 'Singapore',
       'Saint Kitts', 'Sierra Leone', 'Slovenia', 'San Marino',
       'Solomon Islands', 'Somalia', 'Sri Lanka', 'South Sudan',
       'Sao Tome and Principe', 'Sudan', 'Switzerland', 'Suriname',
       'Slovakia', 'Sweden', 'Swaziland', 'Syria', 'Tanzania', 'Tonga',
       'Thailand', 'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Togo',
       'Taiwan', 'Trinidad', 'Tunisia', 'Turkey', 'United Arab Emirates',
       'Uganda', 'Ukraine', 'Uruguay', 'USA', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Saint Vincent', 'Yemen', 'Zambia'],
      dtype=object)

In [27]:
df['Medal'].value_counts()

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64

In [31]:
pd.get_dummies(df['Medal'], dtype = int)

        Bronze  Gold  Silver
0            0     0       0
1            0     0       0
2            0     0       0
3            0     0       0
4            0     0       0
...        ...   ...     ...
221163       0     0       0
221164       0     0       0
221165       0     0       0
221166       0     0       0
221167       0     0       0

[221168 rows x 3 columns]

In [38]:
df =pd.concat([df, pd.get_dummies(df['Medal'], dtype = int)], axis = 1)

In [49]:
medal_tally = df.drop_duplicates(subset = ['Team','NOC', 'Games', 'Year', 'City', 'Sport', 'Event' ,'Medal'])

In [53]:
medal_tally = medal_tally.groupby('NOC').sum()[['Gold','Silver','Bronze']].sort_values('Gold', ascending = False).reset_index()

In [54]:
medal_tally['Total'] = medal_tally['Gold'] + medal_tally['Silver'] + medal_tally['Bronze']

In [55]:
medal_tally

     NOC  Gold  Silver  Bronze  Total
0    USA  1035     802     708   2545
1    URS   394     317     294   1005
2    GBR   278     317     300    895
3    GER   235     261     283    779
4    FRA   234     256     287    777
..   ...   ...     ...     ...    ...
226  WIF     0       0       2      2
227  YEM     0       0       0      0
228  YAR     0       0       0      0
229  YMD     0       0       0      0
230  ZAM     0       1       1      2

[231 rows x 5 columns]

In [115]:
df.dropna(subset=['Year'], inplace=True)
years = df['Year'].astype('int').unique().tolist()
years.sort()
years.insert(0, 'Overall')
years

['Overall',
 1896,
 1900,
 1904,
 1906,
 1908,
 1912,
 1920,
 1924,
 1928,
 1932,
 1936,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016]

In [95]:
country = np.unique(df['region'].dropna().values).tolist()
country.sort()
country.insert(0, 'Overall')

In [96]:
country

['Overall',
 'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Boliva',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Individual Olympic Athletes',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts',
 'Saint Lucia',
 'Saint Vincent',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'UK',
 'USA',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Virgin Islands, British',
 'Virgin Islands, US',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [112]:
df['Year'].isnull().sum()

np.int64(1)